# vmexpect.py script for run-pisd.sh, step 2: root-md.img as md0.
expect login:
send root\r
expect ~ #
send exec /bin/sh\r
expect #
send mount | grep -c '^/dev/md0 on / (ufs, local)' | sed 's/^/MO''UNT /'\r
expect MOUNT 1
send ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub | cut -d' ' -f2 | sed 's/^/HO''STKEY /'\r
expect HOSTKEY @HFP@
send pgrep -x sshd > /dev/null && echo "SSH""D up"\r
expect SSHD up
send shutdown -p now\r
expect Uptime:
